MODULE INCLMESH
IMPLICIT NONE
INTEGER ID, JD, LD, MD, IL, JM, ITMAX, ITMAXT
PARAMETER(ID=129, JD=129, LD=ID, MD=JD)
PARAMETER(IL=ID+LD,JM=JD+MD)
INTEGER IFLAG(ID, JD)
DOUBLE PRECISION RKZ, ETA
DOUBLE PRECISION INCX, INCY, EMAJOR, EMINOR, DLTXYZ(2), RABC(2)
DOUBLE PRECISION XOFFST,YOFFST,XTBEG,XTEND,YTBEG,YTEND
PARAMETER(XOFFST=0, YOFFST=0)
DOUBLE PRECISION XYGCEN(2,ID,JD), EGNS0(4,ID,JD)
DOUBLE PRECISION STRS0(4,ID,JD), STRNS0(4,ID,JD), DISP0(2,ID,JD), EGN0(3)
DOUBLE PRECISION EGNT0(2,ID,JD), EGNTG0(2)
DOUBLE PRECISION LAMDM, LAMDI
DOUBLE PRECISION QHOMO(2,ID,JD), EGNTFLD0(2,ID,JD), SGHOMO(2,ID,JD)
DOUBLE PRECISION DELTA !the length of the computational region in FEM
DOUBLE PRECISION ALFAT !THERMAL EXPANSION
INTEGER NXINC, NYINC !FOR MULTIPLE INHOMO
PARAMETER(NXINC=5, NYINC=5)
DOUBLE PRECISION NXBEG, NXEND, NYBEG, NYEND !FOR MULTIPLE INHOMO
DOUBLE PRECISION NLAMDI(NXINC*NYINC)
DOUBLE PRECISION INCXN(NXINC), INCYN(NYINC)
END MODULE

MODULE INHOMOMT
IMPLICIT NONE
DOUBLE PRECISION EM, VM, EI, VI, DUNDURSA, DUNDURSB
DOUBLE PRECISION EQV, EQVDPI2, EQVDPI4, PI
DOUBLE PRECISION BX,BY,RKAPPA1,RKAPPA2,SHEARM1,SHEARM2
PARAMETER(BY=0.D0)
PARAMETER(PI=DACOS(-1.D0))
INTEGER N, NENEG, NCASE, PSN  !NUMBER OF FIELD POINTS & ENERGY, CASE NUMBER
PARAMETER(N=129, NENEG=5)
END MODULE

SUBROUTINE GETGRID
USE INHOMOMT
USE INCLMESH 
IMPLICIT NONE
INTEGER I, J, K, L, ISINELLP, ISINCUBIC
DOUBLE PRECISION XPOS, YPOS
DOUBLE PRECISION CONSTCL1,R1CL,R2CL,RRCL

SELECT CASE(NCASE)
CASE(1,2,4,5,11)
    XTBEG=INCX-EMAJOR*2.D0
    XTEND=INCX+EMAJOR*2.D0
    YTBEG=INCY-EMINOR*2.D0
    YTEND=INCY+EMINOR*2.D0
CASE(3)
    XTBEG=INCX-EMAJOR*2.D0
    XTEND=INCX+EMAJOR*2.D0
    YTBEG=INCY-EMINOR*2.D0
    YTEND=INCY+EMINOR*2.D0
CASE(6,7,8,9,10)
    XTBEG=INCX-EMAJOR*8.D0
    XTEND=INCX+EMAJOR*8.D0
    YTBEG=INCY-EMINOR*8.D0
    YTEND=INCY+EMINOR*8.D0
END SELECT

DLTXYZ(1)=(XTEND-XTBEG)/DFLOAT(ID)
DLTXYZ(2)=(YTEND-YTBEG)/DFLOAT(JD)

CONSTCL1=BX*(SHEARM1-SHEARM2)/PI/(SHEARM1+SHEARM2)

IFLAG=0
EGNS0(:,:,:)=0.D0
EGNT0(:,:,:)=0.D0

DO I=1,ID
    DO J=1,JD 
    XYGCEN(1,I,J)=XTBEG+(I-0.5D0)*DLTXYZ(1)
    XYGCEN(2,I,J)=YTBEG+(J-0.5D0)*DLTXYZ(2)        
    XPOS=XYGCEN(1,I,J)
    YPOS=XYGCEN(2,I,J)
    
    R1CL=XPOS-RKZ
    R2CL=YPOS-ETA
    RRCL=R1CL*R1CL+R2CL*R2CL

	SELECT CASE(NCASE)
	
		!MULTIPLE RECTANGULAR INHOMO (25)
		CASE(12)
		DO K=1, NXINC; DO L=1, NYINC
			INCXN(K)=NXBEG+(K-1)*(NXEND-NXBEG)/(NXINC-1.D0)
			INCYN(L)=NYBEG+(L-1)*(NYEND-NYBEG)/(NYINC-1.D0)
	        IF(ISINCUBIC(XPOS-INCXN(K), YPOS-INCYN(L)).GT.0) THEN
		       IFLAG(I,J)=(K-1)*5+L
		   
		       EGNS0(1,I,J)=EGN0(1)
		       EGNS0(2,I,J)=EGN0(2)
               EGNS0(3,I,J)=0.D0
		       EGNS0(4,I,J)=EGN0(3)*2.D0
			
		       EGNT0(1,I,J)=EGNTG0(1)
		       EGNT0(2,I,J)=EGNTG0(2)
			ENDIF
		ENDDO;ENDDO
		
		!MULTIPLE CIRCULAR INHOMO (25)
		CASE(13)
		DO K=1, NXINC; DO L=1, NYINC
			INCXN(K)=NXBEG+(K-1)*(NXEND-NXBEG)/(NXINC-1.D0)
			INCYN(L)=NYBEG+(L-1)*(NYEND-NYBEG)/(NYINC-1.D0)
	        IF(ISINELLP(XPOS-INCXN(K), YPOS-INCYN(L)).GT.0) THEN
		       IFLAG(I,J)=(K-1)*5+L
		   
		       EGNS0(1,I,J)=EGN0(1)
		       EGNS0(2,I,J)=EGN0(2)
               EGNS0(3,I,J)=0.D0
		       EGNS0(4,I,J)=EGN0(3)*2.D0
			
		       EGNT0(1,I,J)=EGNTG0(1)
		       EGNT0(2,I,J)=EGNTG0(2)
			ENDIF
		ENDDO;ENDDO
        END SELECT
    ENDDO
ENDDO

RETURN
END

FUNCTION ISINELLP(XPOS, YPOS)
USE INCLMESH
DOUBLE PRECISION VALUE, XPOS, YPOS

VALUE=(XPOS-INCX)*(XPOS-INCX)/EMAJOR/EMAJOR+ &
      (YPOS-INCY)*(YPOS-INCY)/EMINOR/EMINOR

IF(VALUE.LE.1.D0)THEN
    ISINELLP=1
ELSE
    ISINELLP=-1
ENDIF

RETURN
END
 
!20221102 IS IN RECTANGULAR INHOMO
FUNCTION ISINCUBIC(XPOS, YPOS)
USE INCLMESH
DOUBLE PRECISION XPOS, YPOS
     
IF(       ABS(XPOS-INCX)<=RABC(1) &
    .AND. ABS(YPOS-INCY)<=RABC(2)) THEN
                
    ISINCUBIC=1
ELSE
    ISINCUBIC=-1
ENDIF

RETURN
END		
		
