! FFT FOR RECTANGULAR INCLUSION DUE TO EGN-TEMPERATURE GRADIENTS
!COMPUTATE HEAT FLOW
SUBROUTINE HEATFLOW(EGNTS,QFLOWS)
USE INCLMESH
USE INHOMOMT
IMPLICIT NONE
INTEGER IFLOW, JEGNT, KGRP, IY
DOUBLE PRECISION CONST, YYL
DOUBLE PRECISION EGNTS(2, LD, MD), QFLOWS(2, ID, JD)
DOUBLE PRECISION, ALLOCATABLE :: AFLOW(:, :), BEGNT(:, :)
DOUBLE COMPLEX, ALLOCATABLE :: CFFT(:,:), BFFT(:,:) 

QFLOWS(:, :, :)=0.D0 

ALLOCATE(CFFT(IL, JM))
ALLOCATE(BFFT(IL, JM))
ALLOCATE(AFLOW(ID, JD))
ALLOCATE(BEGNT(LD, MD))

DO JEGNT=1, 2
    BEGNT(:, :)=EGNTS(JEGNT, :, :)
    CALL ZEROP2DB(LD, MD, BEGNT, IL, JM, BFFT)
    DO IFLOW=1, 2
        !**************************CONVOLUTION PART************************************
        KGRP=-1
        CALL ICFFTCNV_QFLOW(IFLOW, JEGNT, CFFT) ! WE MAY SAVE [CFFT] TO A BINARY FILE
        CALL CNVFT2CB(ID, JD, LD, MD, CFFT, BFFT, AFLOW)
        QFLOWS(IFLOW,:,:)=QFLOWS(IFLOW,:,:)+AFLOW(:,:)
	        
    ENDDO
ENDDO

! CONSTANT
CONST=0.5D0*LAMDM/PI

QFLOWS(:, :, :)=QFLOWS(:, :, :)*CONST
    
RETURN
END
    
! CONVOLUTION PART
SUBROUTINE ICFFTCNV_QFLOW(IFLOW, JEGNT, CFFT)
USE INCLMESH
USE INHOMOMT
IMPLICIT NONE
INTEGER IFLOW, JEGNT, I, J
DOUBLE PRECISION XYZTS(2), SUM4CORN_QFLOW
DOUBLE COMPLEX CFFT(IL, JM)
DOUBLE PRECISION, ALLOCATABLE :: CI(:, :)

ALLOCATE(CI(-LD: ID-1, -MD: JD-1))

DO I=-LD, ID-1
	XYZTS(1)=XOFFST+DFLOAT(I)*DLTXYZ(1)
	DO J=-MD, JD-1
		XYZTS(2)=YOFFST+DFLOAT(J)*DLTXYZ(2)
		CI(I,J)=SUM4CORN_QFLOW(IFLOW, JEGNT, -1, XYZTS, DLTXYZ) 
	ENDDO
ENDDO

CALL CNVWR2PC(ID, JD, LD, MD, CI, CFFT)

DEALLOCATE(CI)

RETURN
END
    
    
FUNCTION SUM4CORN_QFLOW(HeatN, Num, KGRP, XYZOFF, DLTXYZ)
IMPLICIT NONE
INTEGER HeatN, Num, KGRP, KGRP1
DOUBLE PRECISION XYZOFF(2),DLTXYZ(2)
DOUBLE PRECISION X1, X2, Z1, Z2, QFLOW_I, QFLOW_H, SUM4CORN_QFLOW

X1=XYZOFF(1)-DLTXYZ(1)*0.5D0
X2=XYZOFF(1)+DLTXYZ(1)*0.5D0
Z1=XYZOFF(2)-DLTXYZ(2)*0.5D0
Z2=XYZOFF(2)+DLTXYZ(2)*0.5D0

IF(KGRP == -1) THEN
    SUM4CORN_QFLOW=QFLOW_I(HeatN, Num, X1, Z1)-QFLOW_I(HeatN, Num, X1, Z2)-&
                   QFLOW_I(HeatN, Num, X2, Z1)+QFLOW_I(HeatN, Num, X2, Z2)
    RETURN
ENDIF
    
END