! A UNIFIED GOVERNING EQ. FOR EIM OF HEAT CONDUCTION
SUBROUTINE QTOEGNT(QFLD, TGFLD, EGNTFLD)
USE INCLMESH
USE INHOMOMT
IMPLICIT NONE
INTEGER I, J, K
DOUBLE PRECISION EGNTFLD(2, ID, JD), QFLD(2, ID, JD)
DOUBLE PRECISION A, B, TGFLD(2, ID, JD)

EGNTFLD=0.D0
A=SIGN(1.D0,LAMDI-LAMDM)-SIGN(1.D0,LAMDM-LAMDI)
B=0.25D0*(A+ABS(A))

DO I=1,ID
    DO J=1,JD
		SELECT CASE(NCASE)
			CASE(1,2,3,4,5,6,7,8,9,10,11)
                IF(IFLAG(I,J).GT.0) THEN
               		        EGNTFLD(:,I,J)=0.5D0*ABS(A)*(LAMDM-LAMDI)/LAMDM*(1.D0/LAMDI)**B*&
			                   ((-QFLD(:,I,J))**B+TGFLD(:,I,J)**(1.D0-B)-1.D0)
				ENDIF 
			CASE(12,13) !FOR MULTIPLE INHOMO
                DO K=1, NXINC*NYINC
				    IF(IFLAG(I,J).EQ.K) THEN
		            EGNTFLD(:,I,J)=0.5D0*ABS(A)*(LAMDM-NLAMDI(K))/LAMDM*(1.D0/NLAMDI(K))**B*&
			                       ((-QFLD(:,I,J))**B+TGFLD(:,I,J)**(1.D0-B)-1.D0)
				    ENDIF
				ENDDO
		END SELECT	
    ENDDO
ENDDO

RETURN
END
	
	
! ITERATION OF EGN
SUBROUTINE ITEGNTEMP(DELTTEMP)
USE INHOMOMT
USE INCLMESH
IMPLICIT NONE
INTEGER IT, I, J, K, ISINELLP
DOUBLE PRECISION PXY(2,N), CONST, STRFNL(2,N)
DOUBLE PRECISION XPOS, YPOS, STR(2), INTENEG, FX(NENEG), FY(NENEG)
DOUBLE PRECISION CONST_CIRCL,R2CIRCLE,EGN_CIRCLE(2,ID,JD)

DOUBLE PRECISION EGNTFLDN(2,ID,JD), QLHOMO(2,N), QDISBFLD(2,ID,JD), QFLUXFLD(2,ID,JD)
DOUBLE PRECISION EGNTNOW(2,ID,JD), QNOW(2,ID,JD), CONSTQ
DOUBLE PRECISION EGNTPRE(2,ID,JD), ERRMAXT(2), QFNL(2,N)
DOUBLE PRECISION SGNOW(2,ID,JD), SGDISBFLD(2,ID,JD), TEMPGFLD(2,ID,JD)
DOUBLE PRECISION TEMPFLD(2,ID,JD), TEMPHOMO(2,ID,JD), TEMPDISBFLD(2,ID,JD)
DOUBLE PRECISION SGLHOMO(2,N), SFNL(2,N), CONSTS, DTEMP, TEMPLHOMO(N), TFNL(N)
DOUBLE PRECISION DELTTEMP(ID, JD),QREMOTE

QREMOTE=1.D0
QHOMO(1,:,:)=0.D0
QHOMO(2,:,:)=QREMOTE
SGHOMO=-QHOMO/LAMDM

DTEMP=1.D0*DELTA/LAMDM
!!!PLEASE CHOOSE TEMPFLD(1, I, J) AS THE RESULTANT TEMPERATURE
TEMPHOMO(1,:,:)=-(XYGCEN(2,:,:)+DELTA/2.D0)*QREMOTE/LAMDM

!OUTPUT HEAT FLUX
OPEN(600, FILE="INITIAL_HEAT FLUX.DAT")
OPEN(610, FILE="INITIAL_TEMPERATURE GRADIENT.DAT")
J=(JD+1)/2
DO I=(ID+1)/2, ID  
   WRITE (600,"(4(F20.15))") XYGCEN(1,I,J), XYGCEN(2,I,J),&
                             QHOMO(1,I,J),  QHOMO(2,I,J)
   WRITE (610,"(4(F20.15))") XYGCEN(1,I,J), XYGCEN(2,I,J),&
                             SGHOMO(1,I,J),	SGHOMO(2,I,J)
ENDDO
CLOSE(610)
CLOSE(600)

!TO OBTAIN INTIAL EQUIVALENT EIGEN-TEMPERATURE GRADIENTS
CALL QTOEGNT(QHOMO, SGHOMO, EGNTFLD0)

EGNTNOW=EGNTFLD0

!HEAT PART FOR EQUIVALENT EIGEN-TEMPERATURE GRADIENTS
DO IT=1, ITMAXT
    CALL QNEW(QHOMO, SGHOMO, EGNTNOW, QNOW, SGNOW)
    EGNTPRE=EGNTNOW
    CALL QTOEGNT(QNOW, SGNOW, EGNTNOW)
    EGNTNOW=EGNTNOW

    CALL GETMXERR(ID, JD, 2, EGNTNOW, EGNTPRE, ERRMAXT)
    WRITE(*,*) "  IT_HEAT FLOW=", IT, "  ",  ERRMAXT
ENDDO

!***************************************************************************
!THE FOLLOWING IS TO COMPUTE HEAT FLOW OF FIELD POINTS
EGNTFLDN=EGNTNOW

!!OUTPUT EQUIVALENT EGNTFLDN
OPEN(181, FILE="EGNTFLD-1.DAT")
OPEN(191, FILE="EGNTFLD-2.DAT")
DO J=1, JD
    WRITE(181,'(<ID>F20.10)') (EGNTFLDN(1, I, J), I=1, ID)
    WRITE(191,'(<ID>F20.10)') (EGNTFLDN(2, I, J), I=1, ID)	
ENDDO
CLOSE(191)
CLOSE(181)

!***************************************************************************
!OBTAIN HEAT FLOW DUE TO THE EQUIVALENT EGN-TEMPERATURE GRADIENTS
CALL HEATFLOW(EGNTFLDN,QDISBFLD)
CALL TEMPGRAD(EGNTFLDN,SGDISBFLD)
CALL HFTEMP(EGNTFLDN,TEMPDISBFLD)

OPEN(660, FILE="LINE_DISTB_TEMP_TG_FLUX.DAT")
J=(JD+1)/2
DO I=(ID+1)/2, ID  
   WRITE (660,'(3X, 2F10.5, 5F20.10)') XYGCEN(1,I,J), XYGCEN(2,I,J), TEMPDISBFLD(1,I,J), &
	                                   SGDISBFLD(1, I, J), SGDISBFLD(2, I, J), &
	                                   QDISBFLD(1, I, J), QDISBFLD(2, I, J)
ENDDO
CLOSE(660)

QFLUXFLD=QHOMO+QDISBFLD
TEMPGFLD=SGHOMO+SGDISBFLD
TEMPFLD=TEMPHOMO+TEMPDISBFLD

DELTTEMP(:, :)=TEMPFLD(1, :, :)

OPEN(62, FILE="CONTOUR_HEAT FLUX-1.DAT")
OPEN(63, FILE="CONTOUR_HEAT FLUX-2.DAT")
OPEN(64, FILE="CONTOUR_TEMPERATURE GRADIENT-1.DAT")
OPEN(65, FILE="CONTOUR_TEMPERATURE GRADIENT-2.DAT")
OPEN(66, FILE="CONTOUR_TEMPERATURE.DAT")
DO J=1, JD
    WRITE(62,'(<ID>F20.10)') (QFLUXFLD(1, I, J), I=1, ID)
    WRITE(63,'(<ID>F20.10)') (QFLUXFLD(2, I, J), I=1, ID)	
    WRITE(64,'(<ID>F20.10)') (TEMPGFLD(1, I, J), I=1, ID)
    WRITE(65,'(<ID>F20.10)') (TEMPGFLD(2, I, J), I=1, ID)
	!!!20221205 PLEASE CHOOSE TEMPFLD(1, I, J) AS THE RESULTANT TEMPERATURE
    WRITE(66,'(<ID>F20.10)') (TEMPFLD(1, I, J), I=1, ID)	
ENDDO
CLOSE(66)
CLOSE(65)
CLOSE(64)
CLOSE(63)
CLOSE(62)

OPEN(670, FILE="LINE_TEMP_TG_FLUX.DAT")
I=(ID+1)/2
DO J=1, JD  
   WRITE (670,'(3X, 2F10.5, 5F20.10)') XYGCEN(1,I,J), XYGCEN(2,I,J), TEMPFLD(1,I,J), &
	                                   TEMPGFLD(1, I, J), TEMPGFLD(2, I, J), &
	                                   QFLUXFLD(1, I, J), QFLUXFLD(2, I, J)
ENDDO
CLOSE(670)


SELECT CASE(NCASE)
CASE(1,11)
  	I=(ID+1)/2; K=1
    DO J=1, JD  
		PXY(2,K)=XYGCEN(2,I,J)
		K=K+1
    ENDDO
	
    !SET INITIAL HEAT FLUX ALONG THE TARGET LINE
	!!!NOTE: THE PARAMETERS ARE THE SAME AS QHOMO(1,:,:) & QHOMO(2,:,:)
	QLHOMO(1,:)=0.D0
	QLHOMO(2,:)=QREMOTE
	SGLHOMO=-QLHOMO/LAMDM
	
	DTEMP=1.D0*DELTA/LAMDM
    !!!PLEASE CHOOSE TEMPFLD(1, I, J) AS THE RESULTANT TEMPERATURE
    TEMPLHOMO(:)=-(PXY(1,:)-DELTA/2.D0)*QREMOTE/LAMDM
	
    !CALL SUMSTRFD(N,PXY,EGNFLDN,STRFNL)
	CALL SUMQFD(N,PXY,EGNTFLDN,QLHOMO,QFNL)
	CALL SUMSGRAD(N,PXY,EGNTFLDN,SGLHOMO,SFNL)
	CALL SUMTEMP(N,PXY,EGNTFLDN,TEMPLHOMO,TFNL)

    !NORMALIZED FACTORS
    !CONST=0.5D0/PI*SHEARM1*BX
	CONSTQ=1.D0 !0.5D0*LAMDM/PI
	CONSTS=1.D0 !0.5D0*LAMDM/PI

    !OPEN(6, FILE="FINAL_STR.DAT")
    !DO I=1, N
    !    WRITE(6,'(3X, F10.5, 2F20.10)') PXY(1,I), STRFNL(1,I)/CONST, STRFNL(2,I)/CONST
    !ENDDO
    !CLOSE(6)
	
	OPEN(61, FILE="FINAL_HEAT FLUX.DAT")
    DO I=1, N
        WRITE(61,'(3X, F10.5, 2F20.10)') PXY(2,I), QFNL(1,I)/CONSTQ, QFNL(2,I)/CONSTQ
    ENDDO
    CLOSE(61)
	
	OPEN(661, FILE="FINAL_TEMPERATURE GRADIENT.DAT")
    DO I=1, N
        WRITE(661,'(3X, F10.5, 2F20.10)') PXY(2,I), SFNL(1,I)/CONSTS, SFNL(2,I)/CONSTS
    ENDDO
    CLOSE(661)

	OPEN(662, FILE="FINAL_TEMPERATURE.DAT")
    DO I=1, N
        WRITE(662,'(3X, F10.5, F20.10)') PXY(2,I), TFNL(I)
    ENDDO
    CLOSE(662)	
	
    
SUBROUTINE OUTPUTEGN(EGNFLDN)
USE INHOMOMT
USE INCLMESH 
IMPLICIT NONE
INTEGER I, J, ISINELLP
DOUBLE PRECISION XPOS, YPOS, EGNFLDN(3,ID,JD), ANALYEGN(2,ID,JD)
DOUBLE PRECISION CONSTCL1,RPOLAR,R1CL,R2CL,RRCL

CONSTCL1=-0.5D0*BX*(SHEARM1-SHEARM2)/PI/(SHEARM1+SHEARM2)
OPEN(25, FILE="NUMERCIAL_EGN.DAT")
OPEN(26, FILE="ANALYTICAL_EGN.DAT")
DO I=1,ID
    DO J=1,JD 
        XPOS=XYGCEN(1,I,J)
        YPOS=XYGCEN(2,I,J)
        R1CL=XPOS-RKZ
        R2CL=YPOS-ETA
        RRCL=R1CL*R1CL+R2CL*R2CL
        !THETA=0.5D0*PI: XPOS=YPOS
        !OUTPUT TENSOR SHEAR EGN FOR NUMERICAL EGN
        IF(XPOS.EQ.YPOS .AND. IFLAG(I, J).GT.0 .AND.&
              XPOS.GE.0 .AND. YPOS.GE.0) THEN  
            RPOLAR=SQRT(XPOS*XPOS+YPOS*YPOS)
            WRITE(25,'(3X, F10.5, 2F20.10)') RPOLAR, 0.5D0*EGNFLDN(1,I,J)/CONSTCL1, &
                                                     0.5D0*EGNFLDN(2,I,J)/CONSTCL1

            ANALYEGN(1,I,J)= CONSTCL1*R2CL/RRCL
            ANALYEGN(2,I,J)=-CONSTCL1*R1CL/RRCL
            WRITE(26,'(3X, F10.5, 2F20.10)') RPOLAR, ANALYEGN(1,I,J)/CONSTCL1, &
                                                     ANALYEGN(2,I,J)/CONSTCL1
        ENDIF
    ENDDO
ENDDO
RETURN
END
    
