    
    
SUBROUTINE GETMXERR(NX, NY, NZ, ARR1, ARR2, ERRMAX)
IMPLICIT DOUBLE PRECISION (A-H, O-Z)
DIMENSION ARR1(NZ, NX, NY), ARR2(NZ, NX, NY), ERRMAX(NZ)

DO K=1, NZ
    ERRMAX(K)=0.D0

    DO I=1,NX
        DO J=1,NY
            ERR=DABS(ARR1(K,I,J)-ARR2(K,I,J))
            IF(ERR.GT.ERRMAX(K)) ERRMAX(K)=ERR
        ENDDO
    ENDDO
ENDDO

RETURN
END
    

!SOLVE THE DISTURBED HEAT FLOW & THE APPLIED HOMOGENEOUS HEAT FLOW FIRST
!SECOND, SUM THE HEAT LFOW INSIDE THE INCLUSION DOMAIN
SUBROUTINE QNEW(QQHOMO, SSHOMO, EGNTFLD, QFLD, SGFLD)
USE INCLMESH
IMPLICIT NONE
DOUBLE PRECISION EGNTFLD(2, ID, JD), QFLD(2, ID, JD), SGFLD(2, ID, JD)
DOUBLE PRECISION QQHOMO(2, ID, JD), QDISTB(2, ID, JD)
DOUBLE PRECISION SSHOMO(2, ID, JD), SGDISTB(2, ID, JD)

!20221006 SOLVE THE DISTURBED HEAT FLOW & TEMPERATURE GRADINETS INSIDE THE INCLUSION FIRST
QDISTB(:,:,:)=0.D0
SGDISTB(:,:,:)=0.D0

!PLEASE NOTE THAT INPUT EGN-TEMPERATURE GRADIENTS
CALL HEATFLOW(EGNTFLD,QDISTB)
CALL TEMPGRAD(EGNTFLD,SGDISTB)

!OBTAIN THE HOMOGENEOUS HEAT FLOW INSIDE THE INCLUSION:QFLD0 
!THEN TO OBTAIN THE NEW HEAT FLOW & TEMPERATURE GRADIENTS
QFLD(:,:,:)=QQHOMO(:,:,:)+QDISTB(:,:,:)
SGFLD(:,:,:)=SSHOMO(:,:,:)+SGDISTB(:,:,:)

RETURN
END
     
    

	
