!**********************************************************************
! 2DFFT_HF FOR ELASTIC & THERMAL PROBLEMS
! FOR AN ARBITRARILY SHPAPED INCLUSION & AN EDGE DISLOCATION
! FOR A RIGID INHOMOGENEITY & SOFT MATRIX                    
!***********************************************************************
PROGRAM MAIN
USE INCLMESH
USE INHOMOMT
IMPLICIT NONE
INTEGER TBEG, TEND
DOUBLE PRECISION EGNFLDN(3,ID,JD), DELTTEMP(ID,JD)
CHARACTER*10 DATE1, TIME1 
CHARACTER*10 DATE2, TIME2

CALL DATE_AND_TIME(DATE1, TIME1)
CALL SYSTEM_CLOCK(TBEG)

CALL INPUT

SELECT CASE(NCASE)
CASE(1,11)
    CALL ITEGNTEMP(DELTTEMP)
CALL SYSTEM_CLOCK(TEND)
CALL DATE_AND_TIME(DATE2, TIME2 )

WRITE(*,*) "BEG TIME:",TIME1(1:2), ":" ,TIME1(3:4), ":" ,TIME1(5:10) 
WRITE(*,*) "END TIME:",TIME2(1:2), ":", TIME2(3:4), ":" ,TIME2(5:10) 
WRITE(*,*) "TOL TIME:",TEND-TBEG

OPEN(8, FILE="FINAL_TIME.DAT")
WRITE(8,*) "BEG TIME:",TIME1(1:2), ":" ,TIME1(3:4), ":" ,TIME1(5:10) 
WRITE(8,*) "END TIME:",TIME2(1:2), ":", TIME2(3:4), ":" ,TIME2(5:10) 
WRITE(8,*) "TOL TIME:",TEND-TBEG
CLOSE(8)

END

SUBROUTINE INPUT
USE INCLMESH
USE INHOMOMT
IMPLICIT NONE
DOUBLE PRECISION U2K1P, U1K2P, U2K1M, U1K2M

OPEN(2, FILE="INPUT.DAT")
READ(2, *)NCASE  !FOR INCLUSION SHAPE
READ(2, *)PSN !FOR PLANE STRAIN OR PLANE STRESS
READ(2, *)BX, RKZ, ETA !FOR DISLOCATION
READ(2, *)INCX, INCY, EMAJOR, EMINOR
READ(2, *)RABC(1), RABC(2) !FOR CUBIC INHOMO
READ(2, *)ITMAX
READ(2, *)EM, VM, EI, VI
READ(2, *)EGN0(1), EGN0(2), EGN0(3)
READ(2, *)ITMAXT
READ(2, *)LAMDM, LAMDI
READ(2, *)EGNTG0(1), EGNTG0(2) !THERMAL EXPANSION
READ(2, *)DELTA !the length of the computational region in FEM
READ(2, *)ALFAT !THERMAL EXPANSION
READ(2, *)NXBEG, NXEND, NYBEG, NYEND !REGION FOR MULTIPLE INHOMO
CLOSE(2)

!20240715 !FOR MULTIPLE INHOMO
NLAMDI(:)=0.5D0

SHEARM1=0.5D0*EM/(1.D0+VM)
SHEARM2=0.5D0*EI/(1.D0+VI)

SELECT CASE(PSN)
    CASE(1)
    !FOR PLANE STRAIN
    RKAPPA1=3.D0-4.D0*VM
    RKAPPA2=3.D0-4.D0*VI	
	
    CASE(2)
    !FOR PLANE STRESS
    RKAPPA1=(3.D0-VM)/(1.D0+VM)
    RKAPPA2=(3.D0-VI)/(1.D0+VI)
END SELECT

!DETERMINE DUNDURS PARAMETERS
U2K1P=SHEARM2*(RKAPPA1+1.D0)
U1K2P=SHEARM1*(RKAPPA2+1.D0)
DUNDURSA=(U2K1P-U1K2P)/(U2K1P+U1K2P)

U2K1M=SHEARM2*(RKAPPA1-1.D0)
U1K2M=SHEARM1*(RKAPPA2-1.D0)
DUNDURSB=(U2K1M-U1K2M)/(U2K1P+U1K2P)

CALL GETGRID

RETURN
END
 