SUBROUTINE HFTEMP(EGNTS, TEMPS)
USE INCLMESH
USE INHOMOMT
IMPLICIT NONE
INTEGER ITEMP, JEGNT, KGRP, IY
DOUBLE PRECISION CONST, YYL
DOUBLE PRECISION EGNTS(2, LD, MD), TEMPS(2, ID, JD)
DOUBLE PRECISION, ALLOCATABLE :: ATEMP(:, :), BEGNT(:, :)
DOUBLE COMPLEX, ALLOCATABLE :: CFFT(:,:), BFFT(:,:) 

TEMPS(:, :, :)=0.D0 

ALLOCATE(CFFT(IL, JM))
ALLOCATE(BFFT(IL, JM))
ALLOCATE(ATEMP(ID, JD))
ALLOCATE(BEGNT(LD, MD))

DO JEGNT=1, 2
    BEGNT(:, :)=EGNTS(JEGNT, :, :)
    CALL ZEROP2DB(LD, MD, BEGNT, IL, JM, BFFT)
	DO ITEMP=1, 2
        !**************************CONVOLUTION PART************************************
        KGRP=-1
        CALL ICFFTCNV_TEMP(ITEMP, JEGNT, CFFT) ! WE MAY SAVE [CFFT] TO A BINARY FILE
        CALL CNVFT2CB(ID, JD, LD, MD, CFFT, BFFT, ATEMP)
        TEMPS(ITEMP,:,:)=TEMPS(ITEMP,:,:)+ATEMP(:,:)
	ENDDO
ENDDO

CONST=0.25D0/PI
TEMPS(:, :, :)=TEMPS(:, :, :)*CONST
    
RETURN
END

!CONVOLUTION PART
SUBROUTINE ICFFTCNV_TEMP(ITEMP, JEGNT, CFFT)
USE INCLMESH
IMPLICIT NONE
INTEGER ITEMP, JEGNT, I, J
DOUBLE PRECISION XYZTS(2), SUM4CORN_TEMP
DOUBLE COMPLEX CFFT(IL, JM)
DOUBLE PRECISION, ALLOCATABLE :: CI(:, :)

ALLOCATE(CI(-LD: ID-1, -MD: JD-1))

DO I=-LD, ID-1
	XYZTS(1)=XOFFST+DFLOAT(I)*DLTXYZ(1)
	DO J=-MD, JD-1
		XYZTS(2)=YOFFST+DFLOAT(J)*DLTXYZ(2)
		CI(I,J)=SUM4CORN_TEMP(ITEMP, JEGNT, -1, XYZTS, DLTXYZ) 
	ENDDO
ENDDO

CALL CNVWR2PC(ID, JD, LD, MD, CI, CFFT)

DEALLOCATE(CI)

RETURN
END

   
    
FUNCTION SUM4CORN_TEMP(TEMPN, Num, KGRP, XYZTS, DLTXYZ)
IMPLICIT NONE
INTEGER TEMPN, Num, KGRP, KGRP1
DOUBLE PRECISION XYZTS(2),DLTXYZ(2)
DOUBLE PRECISION X1, X2, Z1, Z2, TEMP_I, TEMP_H, SUM4CORN_TEMP

X1=XYZTS(1)-DLTXYZ(1)*0.5D0
X2=XYZTS(1)+DLTXYZ(1)*0.5D0
Z1=XYZTS(2)-DLTXYZ(2)*0.5D0
Z2=XYZTS(2)+DLTXYZ(2)*0.5D0

IF(KGRP == -1) THEN
    SUM4CORN_TEMP=TEMP_I(TEMPN, Num, X1, Z1)-TEMP_I(TEMPN, Num, X1, Z2)-&
                  TEMP_I(TEMPN, Num, X2, Z1)+TEMP_I(TEMPN, Num, X2, Z2)
    RETURN
ENDIF
    
END