!FFT FOR RECTANGULAR INCLUSION DUE TO EGN-TEMPERATURE GRADIENTS
!COMPUTATE TEMPERATURE GRADIENTS
SUBROUTINE TEMPGRAD(EGNTS,SGRADS)
USE INCLMESH
USE INHOMOMT
IMPLICIT NONE
INTEGER IGRAD, JEGNT, KGRP, IY
DOUBLE PRECISION CONST, YYL
DOUBLE PRECISION EGNTS(2, LD, MD), SGRADS(2, ID, JD)
DOUBLE PRECISION, ALLOCATABLE :: AGRAD(:, :), BEGNT(:, :)
DOUBLE COMPLEX, ALLOCATABLE :: CFFT(:,:), BFFT(:,:) 

SGRADS(:, :, :)=0.D0 

ALLOCATE(CFFT(IL, JM))
ALLOCATE(BFFT(IL, JM))
ALLOCATE(AGRAD(ID, JD))
ALLOCATE(BEGNT(LD, MD))

DO JEGNT=1, 2
    BEGNT(:, :)=EGNTS(JEGNT, :, :)
    CALL ZEROP2DB(LD, MD, BEGNT, IL, JM, BFFT)
    DO IGRAD=1, 2
        !**************************CONVOLUTION PART************************************
        KGRP=-1
        CALL ICFFTCNV_SGRAD(IGRAD, JEGNT, CFFT) ! WE MAY SAVE [CFFT] TO A BINARY FILE
        CALL CNVFT2CB(ID, JD, LD, MD, CFFT, BFFT, AGRAD)
        SGRADS(IGRAD,:,:)=SGRADS(IGRAD,:,:)+AGRAD(:,:)
    ENDDO
ENDDO

!CONSTANT
CONST=0.5D0/PI

SGRADS(:, :, :)=SGRADS(:, :, :)*CONST
    
RETURN
END
    
!CONVOLUTION PART
SUBROUTINE ICFFTCNV_SGRAD(IGRAD, JEGNT, CFFT)
USE INCLMESH
USE INHOMOMT
IMPLICIT NONE
INTEGER IGRAD, JEGNT, I, J
DOUBLE PRECISION XYZTS(2), SUM4CORN_SGRAD
DOUBLE COMPLEX CFFT(IL, JM)
DOUBLE PRECISION, ALLOCATABLE :: CI(:, :)

ALLOCATE(CI(-LD: ID-1, -MD: JD-1))

DO I=-LD, ID-1
	XYZTS(1)=XOFFST+DFLOAT(I)*DLTXYZ(1)
	DO J=-MD, JD-1
		XYZTS(2)=YOFFST+DFLOAT(J)*DLTXYZ(2)
		CI(I,J)=SUM4CORN_SGRAD(IGRAD, JEGNT, -1, XYZTS, DLTXYZ) 
	ENDDO
ENDDO

CALL CNVWR2PC(ID, JD, LD, MD, CI, CFFT)

DEALLOCATE(CI)

RETURN
END
    
    
FUNCTION SUM4CORN_SGRAD(HeatN, Num, KGRP, XYZOFF, DLTXYZ)
IMPLICIT NONE
INTEGER HeatN, Num, KGRP, KGRP1
DOUBLE PRECISION XYZOFF(2),DLTXYZ(2)
DOUBLE PRECISION X1, X2, Z1, Z2, SGRAD_I, SGRAD_H, SUM4CORN_SGRAD

X1=XYZOFF(1)-DLTXYZ(1)*0.5D0
X2=XYZOFF(1)+DLTXYZ(1)*0.5D0
Z1=XYZOFF(2)-DLTXYZ(2)*0.5D0
Z2=XYZOFF(2)+DLTXYZ(2)*0.5D0

IF(KGRP == -1) THEN
    SUM4CORN_SGRAD=SGRAD_I(HeatN, Num, X1, Z1)-SGRAD_I(HeatN, Num, X1, Z2)-&
                   SGRAD_I(HeatN, Num, X2, Z1)+SGRAD_I(HeatN, Num, X2, Z2)
    RETURN
ENDIF
    
END